### PR TITLE
Add coveralls and travis

### PR DESCRIPTION
**Pull request by lukefrake**
#### What are the links to relevant tickets?
[WEB=4542](https://hxshortbreaks.atlassian.net/browse/WEB-4542)
#### What does this PR do?
Add travis.yml and coveralls to this repo
#### What unit tests does this PR have?
It's the tester
#### How should a developer review this?
Make sure travis isn't failing
#### Screenshots (if appropriate)
---
#### Quality checklist (for PR author to complete BEFORE code review):
- [x] I've checked there is appropriate unit test coverage.
- [x] I've updated documentation with any changes to procedures.
- [x] I've tested this cross browser for any visual changes.
- [x] I've checked this work against the requirements of the Jira.
- [x] I am ready for this to be code reviewed, merged and tested.

#### Reviewer 1
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve witnessed the tests running succesfully.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

#### Reviewer 2
- [x] I agree with the assumptions made in the quality checklist.
- [x] I’ve witnessed the work behaving as expected.
- [x] I’ve witnessed the tests running succesfully.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked for coding anti-patterns.
- [x] I've checked this work against the requirements of the Jira.
- [x] I don’t believe this work introduces unnecessary technical debt.
- [x] +1 from me!

### CODE REVIEW

**Comment by MCooke** [comment]
Travis seems to be failing?

**Comment by lukefrake** [comment]
Yeah, it doesn't like Harvest. I have to speak with Mark Terry.

Will just turn travis off until I've spoken with Mark

**Comment by lukefrake** [comment]
I've removed travis for now to get this PR through as I need to move on.

**Comment by MCooke** [comment]
+1 because Travis can't fail if he's not around.

**Comment by philmeehan** [comment]
Why is moving plugin-jsonapi to makeup in scope but not doing the same for this repo?

**Comment by philmeehan** [comment]
+1

**Pull request merged**
